FROM scratch
LABEL org.opencontainers.image.title="GameCastle immutable module catalog"
LABEL org.opencontainers.image.source="https://github.com/${GITHUB_REPOSITORY}"
COPY dist/module-artifact/ /module-artifact/
