var fs = require('fs');
var path = require('path');
var BASE = 'C:/Ai/GameCastle';
var ok = 0, fail = 0;

function edit(relPath, fn) {
  var p = path.join(BASE, relPath);
  var src = fs.readFileSync(p, 'utf8');
  var result = fn(src);
  if (result === src) { console.log('  (no change) ' + relPath); return; }
  if (result === null || result === undefined) { console.log('  FAIL ' + relPath); fail++; return; }
  fs.writeFileSync(p, result, 'utf8');
  console.log('  OK ' + relPath + ' (' + result.split('\n').length + ' lines)');
  ok++;
}

// ═══════════════════════════════════════════════════════════════════════
// 1. game-bridge.js — FULL rewrite (too many changes for patches)
// ═══════════════════════════════════════════════════════════════════════
var newBridge = [
'// GameCastle Game-Network Bridge (v2)',
'// Architecture: Bridge OWNS the game tick. GDevelop is an executor.',
'// Uses RuntimeAdapter for clean GDevelop isolation.',
'// Tick order: capture -> send -> wait remote -> inject -> step -> endFrame',
'',
'var INPUT_SYNC_CHANNEL = "gc:input";',
'',
'function GameCastleNetworkBridge(config) {',
'  config = config || {};',
'  this._declaredInputs = config.inputs || [];',
'  this._tickRate = config.tickRate || 20;',
'  this._sync = config.sync || "local";',
'  this._transport = config.transport || null;',
'  this._adapter = null;',
'  this._game = null;',
'  this._inputManager = null;',
'  this._tick = 0;',
'  this._readyTick = 0;',
'  this._running = false;',
'  this._localInputs = {};',
'  this._remoteInputs = {};',
'  this._orderedInputs = {};',
'  this._peerId = null;',
'  this._inputDelay = config.inputDelay || 2;',
'  this._configRoomId = null;',
'  this._listeners = {};',
'}',
'',
'GameCastleNetworkBridge.prototype.on = function(event, handler) {',
'  if (!this._listeners[event]) this._listeners[event] = [];',
'  this._listeners[event].push(handler);',
'};',
'GameCastleNetworkBridge.prototype._emit = function(event) {',
'  var args = Array.prototype.slice.call(arguments, 1);',
'  var h = this._listeners[event];',
'  if (h) for (var i = 0; i < h.length; i++) h[i].apply(null, args);',
'};',
'',
'GameCastleNetworkBridge.prototype.attach = function(game) {',
'  this._game = game;',
'  this._adapter = new GameCastleRuntimeAdapter(game);',
'  this._adapter.init({ inputs: this._declaredInputs, tickRate: this._tickRate });',
'  this._inputManager = game.getInputManager();',
'};',
'',
'GameCastleNetworkBridge.prototype.start = function() {',
'  var sd = this._game.getSceneAndExtensionsData();',
'  var name = sd ? sd.sceneData.name : null;',
'  if (name) this._game.getSceneStack().replace({ sceneName: name, clear: true });',
'  if (this._sync === "local") this._startLocalLoop();',
'  else this._connectAndStart();',
'};',
'',
'GameCastleNetworkBridge.prototype._startLocalLoop = function() {',
'  if (this._running) return;',
'  this._running = true;',
'  var self = this;',
'  this._adapter.startLoop(function(dt, tick) {',
'    self._adapter.stepSimulation(dt);',
'    self._adapter.endFrame();',
'    self._emit("tick", tick, self._adapter.captureInputs());',
'    self._tick = tick;',
'  });',
'};',
'',
'GameCastleNetworkBridge.prototype._connectAndStart = function() {',
'  if (!this._transport) { this._startLocalLoop(); return; }',
'  var self = this;',
'  this._transport.connect().then(function() {',
'    self._transport.on("game_input", function(from, tick, inputs) {',
'      self._remoteInputs[tick] = inputs;',
'      self._tryAdvanceLockstep();',
'    });',
'    self._transport.on("game_state", function(tick, ordered) {',
'      self._orderedInputs[tick] = ordered;',
'      self._tryAdvanceAuthority();',
'    });',
'    self._transport.on("sync", function(from, ch, data) {',
'      if (ch === INPUT_SYNC_CHANNEL && data) {',
'        self._remoteInputs[data.tick] = data.inputs;',
'        self._tryAdvanceLockstep();',
'      }',
'    });',
'    self._transport.on("player_joined", function(pid) {',
'      if (pid !== self._transport.getPlayerId()) {',
'        self._peerId = pid;',
'        self._emit("peer_joined", pid);',
'      }',
'    });',
'    self._transport.on("player_left", function(pid) {',
'      if (pid === self._peerId) { self._peerId = null; self._emit("peer_left", pid); }',
'    });',
'    self._transport.on("joined", function() { self._startNetworkLoop(); });',
'    if (self._configRoomId) self._transport.joinRoom(self._configRoomId);',
'    else {',
'      self._transport.on("room_created", function(rid) { self._transport.joinRoom(rid); });',
'      self._transport.createRoom({ tickRate: self._tickRate });',
'    }',
'  }).catch(function() { self._startLocalLoop(); });',
'};',
'',
'GameCastleNetworkBridge.prototype._startNetworkLoop = function() {',
'  if (this._running) return;',
'  this._running = true;',
'  var self = this;',
'  this._adapter.startLoop(function(dt, tick) {',
'    return self._onNetworkTick(dt, tick);',
'  });',
'};',
'',
'GameCastleNetworkBridge.prototype._onNetworkTick = function(dt, tick) {',
'  switch (this._sync) {',
'    case "lockstep": case "lockstep-input": return this._tickLockstep(dt, tick);',
'    case "server-authoritative": return this._tickAuthority(dt, tick);',
'    default: this._adapter.stepSimulation(dt); this._adapter.endFrame(); return true;',
'  }',
'};',
'',
'GameCastleNetworkBridge.prototype._tickLockstep = function(dt, tick) {',
'  this._localInputs[tick] = this._adapter.captureInputs();',
'  if (this._peerId) this._transport.sync(INPUT_SYNC_CHANNEL, { tick: tick, inputs: this._localInputs[tick] });',
'  this._tick = tick;',
'  this._tryAdvanceLockstep();',
'  return true;',
'};',
'',
'GameCastleNetworkBridge.prototype._tryAdvanceLockstep = function() {',
'  while (this._running) {',
'    var tick = this._readyTick;',
'    if (tick + this._inputDelay >= this._tick) break;',
'    if (this._localInputs[tick] === undefined) break;',
'    // Solo mode: advance without waiting for remote',
'    if (this._peerId && this._remoteInputs[tick] === undefined) break;',
'    if (this._peerId && this._remoteInputs[tick]) {',
'      this._adapter.injectInputs(this._remoteInputs[tick], false);',
'    }',
'    this._adapter.stepSimulation(1000 / this._tickRate);',
'    this._adapter.endFrame();',
'    this._emit("advance", tick, this._localInputs[tick], this._remoteInputs[tick] || null);',
'    delete this._localInputs[tick - 60];',
'    delete this._remoteInputs[tick - 60];',
'    this._readyTick++;',
'  }',
'};',
'',
'GameCastleNetworkBridge.prototype._tickAuthority = function(dt, tick) {',
'  var inputs = this._adapter.captureInputs();',
'  if (this._transport && this._transport.sendGameInput) this._transport.sendGameInput(tick, inputs);',
'  this._tick = tick;',
'  this._tryAdvanceAuthority();',
'  return true;',
'};',
'',
'GameCastleNetworkBridge.prototype._tryAdvanceAuthority = function() {',
'  while (this._running) {',
'    var tick = this._readyTick;',
'    if (tick + this._inputDelay >= this._tick) break;',
'    var ordered = this._orderedInputs[tick];',
'    if (!ordered) break;',
'    var self = this;',
'    var myId = this._transport ? this._transport.getPlayerId() : null;',
'    Object.keys(ordered).forEach(function(pid) {',
'      if (pid !== myId) self._adapter.injectInputs(ordered[pid], false);',
'    });',
'    this._adapter.stepSimulation(1000 / this._tickRate);',
'    this._adapter.endFrame();',
'    this._emit("advance", tick, ordered);',
'    delete this._orderedInputs[tick - 60];',
'    this._readyTick++;',
'  }',
'};',
'',
'GameCastleNetworkBridge.prototype.setRoomId = function(id) { this._configRoomId = id; };',
'GameCastleNetworkBridge.prototype.getAdapter = function() { return this._adapter; };',
'GameCastleNetworkBridge.prototype.getTick = function() { return this._tick; };',
'GameCastleNetworkBridge.prototype.getReadyTick = function() { return this._readyTick; };',
'GameCastleNetworkBridge.prototype.isRunning = function() { return this._running; };',
'GameCastleNetworkBridge.prototype.getPeerId = function() { return this._peerId; };',
'',
'GameCastleNetworkBridge.prototype.detach = function() {'
