// _apply_fixes.js - writes all corrected networking files
var fs = require('fs');
var path = require('path');
var BASE = 'C:/Ai/GameCastle';

function writeFile(relPath, content) {
  var p = path.join(BASE, relPath);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content, 'utf8');
  console.log('OK: ' + relPath + ' (' + content.split('\n').length + ' lines)');
}

// =========================================================================
// 1. runtime-adapter.js (fixed: no _getFirstSceneName)
// =========================================================================
writeFile('ai/network-runtime/runtime-adapter.js', [
'// GameCastle Runtime Adapter',
'// Isolates GDevelop game loop behind a clean public-API-only interface.',
'// Uses ONLY public GDevelop APIs: onKeyPressed, onKeyReleased, isKeyPressed,',
'// onFrameEnded, sceneStack.step, sceneStack.renderWithoutStep, loadAllAssets.',
'// Does NOT touch _keys, _pressedKeys, or any GDevelop private fields.',
'',
'var GC_ADAPTER_KEY_MAP = {',
'  move_up:    "ArrowUp",',
'  move_down:  "ArrowDown",',
'  move_left:  "ArrowLeft",',
'  move_right: "ArrowRight",',
'  shoot:      "Space",',
'  jump:       "Space",',
'  start:      "Enter",',
'  restart:    "KeyR",',
'  action1:    "KeyZ",',
'  action2:    "KeyX",',
'  action3:    "KeyC",',
'};',
'',
'var _KEY_NAME_TO_CODE = {',
'  "ArrowUp":38, "ArrowDown":40, "ArrowLeft":37, "ArrowRight":39,',
'  "Space":32, "Enter":13, "KeyR":82,',
'  "KeyZ":90, "KeyX":88, "KeyC":67,',
'  "KeyA":65, "KeyS":83, "KeyD":68, "KeyW":87,',
'  "ShiftLeft":16, "ShiftRight":16,',
'  "Escape":27, "Tab":9,',
'};',
'',
'function _keyNameToCode(name) {',
'  return _KEY_NAME_TO_CODE[name] !== undefined ? _KEY_NAME_TO_CODE[name] : null;',
'}',
'',
'function GameCastleRuntimeAdapter(game) {',
'  this._game = game;',
'  this._sceneStack = null;',
'  this._inputManager = null;',
'  this._renderer = null;',
'  this._declaredInputs = [];',
'  this._inputMap = {};',
'  this._rAFId = null;',
'  this._tickFn = null;',
'  this._running = false;',
'  this._tickRate = 20;',
'  this._tickIntervalMs = 50;',
'  this._accumulator = 0;',
'  this._lastFrameTime = 0;',
'  this._totalTicks = 0;',
'}',
'',
'GameCastleRuntimeAdapter.prototype.init = function (config) {',
'  config = config || {};',
'  var self = this;',
'',
'  this._sceneStack = this._game.getSceneStack();',
'  this._inputManager = this._game.getInputManager();',
'  this._renderer = this._game.getRenderer();',
'  this._declaredInputs = config.inputs || [];',
'  this._tickRate = config.tickRate || 20;',
'  this._tickIntervalMs = Math.round(1000 / this._tickRate);',
'',
'  this._inputMap = {};',
'  var map = config.keyMap || GC_ADAPTER_KEY_MAP;',
'  for (var i = 0; i < this._declaredInputs.length; i++) {',
'    var inputName = this._declaredInputs[i];',
'    var keyName = map[inputName];',
'    if (keyName) this._inputMap[inputName] = keyName;',
'  }',
'',
'  // Public API: get first scene name.',
'  // Uses getSceneAndExtensionsData() without args to get first scene.',
'  var sceneData = this._game.getSceneAndExtensionsData();',
'  var firstScene = sceneData ? sceneData.sceneData.name : null;',
'  if (!firstScene) {',
'    return Promise.reject(new Error("No scene found in game data"));',
'  }',
'',
'  return this._game.loadAllAssets(function () {',
'    self._sceneStack.replace({ sceneName: firstScene, clear: true });',
'  });',
'};',
'',
'GameCastleRuntimeAdapter.prototype.startLoop = function (tickFn) {',
'  if (this._running) return;',
'  this._running = true;',
'  this._tickFn = tickFn;',
'  this._lastFrameTime = performance.now();',
'  this._accumulator = 0;',
'  this._totalTicks = 0;',
'  var self = this;',
'  var maxCatchupMs = 200;',
'',
'  function frame(now) {',
'    if (!self._running) return;',
'    self._rAFId = requestAnimationFrame(frame);',
'    var rawDelta = now - self._lastFrameTime;',
'    self._lastFrameTime = now;',
'    if (rawDelta > maxCatchupMs) rawDelta = maxCatchupMs;',
'    self._accumulator += rawDelta;',
'    while (self._accumulator >= self._tickIntervalMs) {',
'      self._accumulator -= self._tickIntervalMs;',
'      self._totalTicks++;',
'      if (self._tickFn) {',
'        var ok = self._tickFn(self._tickIntervalMs, self._totalTicks);',
'        if (ok === false) { self.stopLoop(); return; }',
'      }',
'    }',
'    self.render();',
'  }',
'  this._rAFId = requestAnimationFrame(frame);',
'};',
'',
'GameCastleRuntimeAdapter.prototype.stopLoop = function () {',
'  this._running = false;',
'  if (this._rAFId) { cancelAnimationFrame(this._rAFId); this._rAFId = null; }',
'};',
'',
'GameCastleRuntimeAdapter.prototype.stepSimulation = function (dtMs) {',
'  if (!this._sceneStack) return false;',
'  return this._sceneStack.step(dtMs);',
'};',
'',
'GameCastleRuntimeAdapter.prototype.captureInputs = function () {',
'  if (!this._inputManager) return {};',
'  var frame = {};',
'  var im = this._inputManager;',
'  for (var i = 0; i < this._declaredInputs.length; i++) {',
'    var name = this._declaredInputs[i];',
'    var key = this._inputMap[name];',
'    if (key) frame[name] = im.isKeyPressed(key);',
'  }',
'  return frame;',
'};',
'',
'GameCastleRuntimeAdapter.prototype.injectInputs = function (frame, isLocal) {',
'  if (!this._inputManager || isLocal) return;',
'  var im = this._inputManager;',
'  im.releaseAllPressedKeys();',
'  for (var i = 0; i < this._declaredInputs.length; i++) {',
'    var name = this._declaredInputs[i];',
'    var key = this._inputMap[name];',
'    if (!key || !frame[name]) continue;',
'    var code = _keyNameToCode(key);',
'    if (code !== null) im.onKeyPressed(code);',
'  }',
'};',
'',
'GameCastleRuntimeAdapter.prototype.endFrame = function () {',
'  if (this._inputManager) this._inputManager.onFrameEnded();',
'};',
'',
'GameCastleRuntimeAdapter.prototype.render = function () {',
'  if (this._sceneStack) this._sceneStack.renderWithoutStep();',
'};',
'',
'GameCastleRuntimeAdapter.prototype.getStateHash = function () {',
'  try {',
'    var scene = this._sceneStack ? this._sceneStack.getCurrentScene() : null;',
'    if (!scene) return "nosce";',
'    var data = scene.getNetworkSyncData({ playerNumber:1, isHost:true, syncGameVariables:true, syncLayers:true, syncSceneTimers:true });',
'    if (!data) return "empty";',
'    var json = JSON.stringify(data);',
'    var hash = 5381;',
'    for (var i = 0; i < json.length; i++) hash = ((hash << 5) + hash + json.charCodeAt(i)) | 0;',
'    return (hash >>> 0).toString(16);',
'  } catch(e) { return "err:" + e.message; }',
'};',
'',
'GameCastleRuntimeAdapter.prototype.getTickCount = function () { return this._totalTicks; };',
'GameCastleRuntimeAdapter.prototype.isRunning = function () { return this._running; };',
'GameCastleRuntimeAdapter.prototype.getTickIntervalMs = function () { return this._tickIntervalMs; };',
'',
'if (typeof module !== "undefined") {',
'  module.exports = { GameCastleRuntimeAdapter: GameCastleRuntimeAdapter, GC_ADAPTER_KEY_MAP: GC_ADAPTER_KEY_MAP };',
'}',
].join('\n'));

console.log('\n--- Step 1: runtime-adapter.js done ---\n');
