var fs = require('fs');
var lines = [];

function L(s) { lines.push(s); }

L('// GameCastle Game-Network Bridge (v2)');
L('// Architecture: Bridge OWNS the game tick. GDevelop is an executor.');
L('// Uses RuntimeAdapter - no GDevelop private field access.');
L('');
L('var INPUT_SYNC_CHANNEL = "gc:input";');
L('');
L('function GameCastleNetworkBridge(config) {');
L('  config = config || {};');
L('  this._declaredInputs = config.inputs || [];');
L('  this._tickRate = config.tickRate || 20;');
L('  this._sync = config.sync || "local";');
L('  this._transport = config.transport || null;');
L('  this._adapter = null;');
L('  this._game = null;');
L('  this._tick = 0;');
L('  this._readyTick = 0;');
L('  this._running = false;');
L('  this._localInputs = {};');
L('  this._remoteInputs = {};');
L('  this._orderedInputs = {};');
L('  this._peerId = null;');
L('  this._inputDelay = config.inputDelay || 2;');
L('  this._configRoomId = null;');
L('  this._listeners = {};');
L('}');
L('');
L('GameCastleNetworkBridge.prototype.on = function(event, handler) {');
L('  if (!this._listeners[event]) this._listeners[event] = [];');
L('  this._listeners[event].push(handler);');
L('};');
L('');
L('GameCastleNetworkBridge.prototype._emit = function(event) {');
L('  var args = Array.prototype.slice.call(arguments, 1);');
L('  var handlers = this._listeners[event];');
L('  if (handlers) {');
L('    for (var i = 0; i < handlers.length; i++) handlers[i].apply(null, args);');
L('  }');
L('};');
L('');
L('GameCastleNetworkBridge.prototype.attach = function (game) {');
L('  this._game = game;');
L('  this._adapter = new GameCastleRuntimeAdapter(game);');
L('  var self = this;');
L('  return this._adapter.init({');
L('    inputs: this._declaredInputs,');
L('    tickRate: this._tickRate,');
L('  }).then(function () {');
L('    if (self._sync === "local") {');
L('      self._startLocalLoop();');
L('    } else {');
L('      self._connectAndStart();');
L('    }');
L('  });');
L('};');
L('');
L('GameCastleNetworkBridge.prototype._startLocalLoop = function () {');
L('  if (this._running) return;');
L('  this._running = true;');
L('  var self = this;');
L('  this._adapter.startLoop(function (dtMs, tickNum) {');
L('    var inputs = self._adapter.captureInputs();');
L('    self._adapter.stepSimulation(dtMs);');
L('    self._adapter.endFrame();');
L('    self._emit("tick", tickNum, inputs);');
L('    self._tick = tickNum;');
L('  });');
L('};');
L('');
L('GameCastleNetworkBridge.prototype._connectAndStart = function () {');
L('  if (!this._transport) { this._startLocalLoop(); return; }');
L('  var self = this;');
L('  this._transport.connect().then(function () {');
L('    self._transport.on("game_input", function (from, tick, inputs) {');
L('      self._onRemoteInput(from, tick, inputs);');
L('    });');
L('    self._transport.on("game_state", function (tick, orderedInputs) {');
L('      self._onServerState(tick, orderedInputs);');
L('    });');
L('    self._transport.on("sync", function (from, channel, data) {');
L('      if (channel === INPUT_SYNC_CHANNEL && data) {');
L('        self._onRemoteInput(from, data.tick, data.inputs);');
L('      }');
L('    });');
L('    self._transport.on("player_joined", function (playerId) {');
L('      if (playerId !== self._transport.getPlayerId()) {');
L('        self._peerId = playerId;');
L('        self._emit("peer_joined", playerId);');
L('      }');
L('    });');
L('    self._transport.on("player_left", function (playerId) {');
L('      if (playerId === self._peerId) {');
L('        self._peerId = null;');
L('        self._emit("peer_left", playerId);');
L('      }');
L('    });');
L('    self._transport.on("joined", function () {');
L('      self._startNetworkLoop();');
L('    });');
L('    if (self._configRoomId) {');
L('      self._transport.joinRoom(self._configRoomId);');
L('    } else {');
L('      self._transport.on("room_created", function (roomId) {');
L('        self._transport.joinRoom(roomId);');
L('      });');
L('      self._transport.createRoom({ tickRate: self._tickRate });');
L('    }');
L('  }).catch(function () {');
L('    self._startLocalLoop();');
L('  });');
L('};');
L('');
L('GameCastleNetworkBridge.prototype._startNetworkLoop = function () {');
L('  if (this._running) return;');
L('  this._running = true;');
L('  var self = this;');
L('  this._adapter.startLoop(function (dtMs, tickNum) {');
L('    return self._onNetworkTick(dtMs, tickNum);');
L('  });');
L('};');
L('');
L('GameCastleNetworkBridge.prototype._onNetworkTick = function (dtMs, tickNum) {');
L('  var tick = tickNum;');
L('  switch (this._sync) {');
L('    case "lockstep":');
L('    case "lockstep-input":');
L('      return this._tickLockstep(dtMs, tick);');
L('    case "server-authoritative":');
L('      return this._tickAuthority(dtMs, tick);');
L('    default:');
L('      this._adapter.stepSimulation(dtMs);');
L('      this._adapter.endFrame();');
L('      return true;');
L('  }');
L('};');
L('');
L('GameCastleNetworkBridge.prototype._tickLockstep = function (dtMs, tick) {');
L('  var localInputs = this._adapter.captureInputs();');
L('  this._localInputs[tick] = localInputs;');
L('  this._sendInputs(tick, localInputs);');
L('  this._tick = tick;');
L('  this._tryAdvanceLockstep();');
L('  return true;');
L('};');
L('');
L('GameCastleNetworkBridge.prototype._tryAdvanceLockstep = function () {');
L('  var self = this;');
L('  while (this._running) {');
L('    var tick = this._readyTick;');
L('    if (tick + this._inputDelay >= this._tick) break;');
L('    if (this._localInputs[tick] === undefined) break;');
L('    if (this._remoteInputs[tick] === undefined) break;');
L('    var remote = this._remoteInputs[tick];');
L('    this._adapter.injectInputs(remote, false);');
L('    this._adapter.stepSimulation(this._adapter.getTickIntervalMs());');
L('    this._adapter.endFrame();');
L('    this._emit("advance", tick, this._localInputs[tick], remote);');
L('    var cutoff = tick - 60;');
L('    delete this._localInputs[cutoff];');
L('    delete this._remoteInputs[cutoff];');
L('    this._readyTick++;');
L('  }');
L('};');
L('');
L('GameCastleNetworkBridge.prototype._tickAuthority = function (dtMs, tick) {');
L('  var localInputs = this._adapter.captureInputs();');
L('  if (this._transport && this._transport.sendGameInput) {');
L('    this._transport.sendGameInput(tick, localInputs);');
L('  }');
L('  this._tick = tick;');
L('  this._tryAdvanceAuthority();');
L('  return true;');
L('};');
L('');
L('GameCastleNetworkBridge.prototype._tryAdvanceAuthority = function () {');
L('  while (this._running) {');
L('    var tick = this._readyTick;');
L('    if (tick + this._inputDelay >= this._tick) break;');
L('    var ordered = this._orderedInputs[tick];');
L('    if (!ordered) break;');
L('    var self = this;');
L('    var myId = this._transport ? this._transport.getPlayerId() : null;');
L('    Object.keys(ordered).forEach(function (playerId) {');
L('      if (playerId !== myId) {');
L('        self._adapter.injectInputs(ordered[playerId], false);');
L('      }');
L('    });');
L('    this._adapter.stepSimulation(this._adapter.getTickIntervalMs());');
L('    this._adapter.endFrame();');
L('    this._emit("advance", tick, ordered);');
L('    var cutoff = tick - 60;');
L('    delete this._orderedInputs[cutoff];');
L('    this._readyTick++;');
L('  }');
L('};');
L('');
L('GameCastleNetworkBridge.prototype._sendInputs = function (tick, inputs) {');
L('  if (!this._transport) return;');
L('  if (this._peerId) {');
L('    this._transport.sendTo(this._peerId, {');
L('      __gc: { type: "input", tick: tick, inputs: inputs }');
L('    });');
L('  } else {');
L('    this._transport.sync(INPUT_SYNC_CHANNEL, { tick: tick, inputs: inputs });');
L('  }');
L('  if (this._transport.sendGameInput) {');
L('    this._transport.sendGameInput(tick, inputs);');
L('  }');
L('};');
L('');
L('GameCastleNetworkBridge.prototype._onRemoteInput = function (fromPlayerId, tick, inputs) {');
L('  this._remoteInputs[tick] = inputs;');
L('  this._tryAdvanceLockstep();');
L('};');
L('');
L('GameCastleNetworkBridge.prototype._onServerSt
