var fs = require('fs');
var path = require('path');

var content = [
'// GameCastle Game-Network Bridge (v2)',
'// Architecture: Bridge OWNS the game tick. GDevelop is an executor.',
'// Uses RuntimeAdapter for clean GDevelop isolation.',
'// Does NOT touch GDevelop private fields.',
'//',
'// Tick order (lockstep):',
'//   1. capture local input for tick N',
'//   2. send input(N) to peer',
'//   3. wait until remote input for tick N arrives',
'//   4. inject local + remote inputs into runtime',
'//   5. step simulation one fixed tick',
'//   6. endFrame (reset per-frame input state)',
'',
'var INPUT_SYNC_CHANNEL = "gc:input";',
'',
'function GameCastleNetworkBridge(config) {',
'  config = config || {};',
'  this._declaredInputs = config.inputs || [];',
'  this._tickRate = config.tickRate || 20;',
'  this._sync = config.sync || "local";',
'  this._transport = config.transport || null;',
'  this._adapter = null;',
'  this._game = null;',
'  this._tick = 0;',
'  this._readyTick = 0;',
'  this._running = false;',
'  this._localInputs = {};',
'  this._remoteInputs = {};',
'  this._orderedInputs = {};',
'  this._peerId = null;',
'  this._inputDelay = config.inputDelay || 2;',
'  this._configRoomId = null;',
'  this._listeners = {};',
'}',
'',
'GameCastleNetworkBridge.prototype.on = function(event, handler) {',
'  if (!this._listeners[event]) this._listeners[event] = [];',
'  this._listeners[event].push(handler);',
'};',
'',
'GameCastleNetworkBridge.prototype._emit = function(event) {',
'  var args = Array.prototype.slice.call(arguments, 1);',
'  var handlers = this._listeners[event];',
'  if (handlers) {',
'    for (var i = 0; i < handlers.length; i++) handlers[i].apply(null, args);',
'  }',
'};',
'',
'// Attach to a GDevelop RuntimeGame. Returns Promise.',
'GameCastleNetworkBridge.prototype.attach = function (game) {',
'  this._game = game;',
'  this._adapter = new GameCastleRuntimeAdapter(game);',
'  var self = this;',
'  return this._adapter.init({',
'    inputs: this._declaredInputs,',
'    tickRate: this._tickRate,',
'  }).then(function () {',
'    if (self._sync === "local") {',
'      self._startLocalLoop();',
'    } else {',
'      self._connectAndStart();',
'    }',
'  });',
'};',
'',
'// ---- Local loop ----',
'',
'GameCastleNetworkBridge.prototype._startLocalLoop = function () {',
'  if (this._running) return;',
'  this._running = true;',
'  var self = this;',
'  this._adapter.startLoop(function (dtMs, tickNum) {',
'    var inputs = self._adapter.captureInputs();',
'    self._adapter.stepSimulation(dtMs);',
'    self._adapter.endFrame();',
'    self._emit("tick", tickNum, inputs);',
'    self._tick = tickNum;',
'  });',
'};',
'',
'// ---- Network connect ----',
'',
'GameCastleNetworkBridge.prototype._connectAndStart = function () {',
'  if (!this._transport) {',
'    this._startLocalLoop();',
'    return;',
'  }',
'  var self = this;',
'  this._transport.connect().then(function () {',
'    self._transport.on("game_input", function (from, tick, inputs) {',
'      self._onRemoteInput(from, tick, inputs);',
'    });',
'    self._transport.on("game_state", function (tick, orderedInputs) {',
'      self._onServerState(tick, orderedInputs);',
'    });',
'    self._transport.on("sync", function (from, channel, data) {',
'      if (channel === INPUT_SYNC_CHANNEL && data) {',
'        self._onRemoteInput(from, data.tick, data.inputs);',
'      }',
'    });',
'    self._transport.on("player_joined", function (playerId) {',
'      if (playerId !== self._transport.getPlayerId()) {',
'        self._peerId = playerId;',
'        self._emit("peer_joined", playerId);',
'      }',
'    });',
'    self._transport.on("player_left", function (playerId) {',
'      if (playerId === self._peerId) {',
'        self._peerId = null;',
'        self._emit("peer_left", playerId);',
'      }',
'    });',
'    self._transport.on("joined", function () {',
'      self._startNetworkLoop();',
'    });',
'    if (self._configRoomId) {',
'      self._transport.joinRoom(self._configRoomId);',
'    } else {',
'      self._transport.on("room_created", function (roomId) {',
'        self._transport.joinRoom(roomId);',
'      });',
'      self._transport.createRoom({ tickRate: self._tickRate });',
'    }',
'  }).catch(function () {',
'    self._startLocalLoop();',
'  });',
'};',
'',
'// ---- Network loop ----',
'',
'GameCastleNetworkBridge.prototype._startNetworkLoop = function () {',
'  if (this._running) return;',
'  this._running = true;',
'  var self = this;',
'  this._adapter.startLoop(function (dtMs, tickNum) {',
'    return self._onNetworkTick(dtMs, tickNum);',
'  });',
'};',
'',
'GameCastleNetworkBridge.prototype._onNetworkTick = function (dtMs, tickNum) {',
'  var tick = tickNum;',
'  switch (this._sync) {',
'    case "lockstep":',
'    case "lockstep-input":',
'      return this._tickLockstep(dtMs, tick);',
'    case "server-authoritative":',
'      return this._tickAuthority(dtMs, tick);',
'    default:',
'      this._adapter.stepSimulation(dtMs);',
'      this._adapter.endFrame();',
'      return true;',
'  }',
'};',
'',
'// ---- Lockstep tick ----',
'// Per tick: capture -> send -> buffer -> check remote -> inject -> step -> endFrame',
'',
'GameCastleNetworkBridge.prototype._tickLockstep = function (dtMs, tick) {',
'  var localInputs = this._adapter.captureInputs();',
'  this._localInputs[tick] = localInputs;',
'  this._sendInputs(tick, localInputs);',
'  this._tick = tick;',
'  this._tryAdvanceLockstep();',
'  return true;',
'};',
'',
'GameCastleNetworkBridge.prototype._tryAdvanceLockstep = function () {',
'  var self = this;',
'  while (this._running) {',
'    var tick = this._readyTick;',
'    if (tick + this._inputDelay >= this._tick) break;',
'    if (this._localInputs[tick] === undefined) break;',
'    if (this._remoteInputs[tick] === undefined) break;',
'    var remote = this._remoteInputs[tick];',
'    this._adapter.injectInputs(remote, false);',
'    this._adapter.stepSimulation(this._adapter.getTickIntervalMs());',
'    this._adapter.endFrame();',
'    this._emit("advance", tick, this._localInputs[tick], remote);',
'    var cutoff = tick - 60;',
'    delete this._localInputs[cutoff];',
'    delete this._remoteInputs[cutoff];',
'    this._readyTick++;',
'  }',
'};',
'',
'// ---- Authority tick ----',
'',
'GameCastleNetworkBridge.prototype._tickAuthority = function (dtMs, tick) {',
'  var localInputs = this._adapter.captureInputs();',
'  if (this._transport && this._transport.sendGameInput) {',
'    this._transport.sendGameInput(tick, localInputs);',
'  }',
'  this._tick = tick;',
'  this._tryAdvanceAuthority();',
'  return true;',
'};',
'',
'GameCastleNetworkBridge.prototype._tryAdvanceAuthority = function () {',
'  while (this._running) {',
'    var tick = this._readyTick;',
'    if (tick + this._inputDelay >= this._tick) break;',
'    var ordered = this._orderedInputs[tick];',
'    if (!ordered) break;',
'    var self = this;',
'    var myId = this._transport ? this._transport.getPlayerId() : null;',
'    Object.keys(ordered).forEach(function (playerId) {',
'      if (playerId !== myId) {',
'        self._adapter.injectInputs(ordered[playerId], false);',
'      }',
'    });',
'    this._adapter.stepSimulation(this._adapter.getTickIntervalMs());',
'    this._adapter.endFrame();',
'    this._emit("advance", tick, ordered);',
'    var cutoff = tick - 60;',
'    delete this._orderedInputs[cutoff];',
'    this._readyTick++;',
'  }',
'};',
'',
'// ---- Input send/receive ----',
'',
'GameCastleNetworkBridge.prototype._sendInputs = function (tick, inputs) {',
'  if (!this._transport) return;',
'  if (this._peerId) {',
'    this._transport.sendTo(this._peerId, {',
'      __gc: { type: "input", tick: tick, inputs: inputs }',
'    });',
'  } else {',
'    this._transport.sync(INPUT_SYNC_CHANNEL, { tick: tick, inputs: inputs });',
'  }',
'  if (this._transport.sendGameInput) {',
'    this._transport.sendGameInput(tick, inputs);',
'  }',
'};',
'',
'GameCastleNetworkBridge.prototype._onRemoteInput = function (fromPlayerId, tick, inputs) {',
'  this._remoteInputs[tick] = inputs;',
'  this._t
